/*
 * This file is generated by jOOQ.
*/
package database.tables;


import database.DefaultSchema;
import database.Indexes;
import database.Keys;
import database.tables.records.WidgetRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Widget extends TableImpl<WidgetRecord> {

    private static final long serialVersionUID = 103351814;

    /**
     * The reference instance of <code>Widget</code>
     */
    public static final Widget WIDGET = new Widget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WidgetRecord> getRecordType() {
        return WidgetRecord.class;
    }

    /**
     * The column <code>Widget.WidgetId</code>.
     */
    public final TableField<WidgetRecord, Integer> WIDGETID = createField("WidgetId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Widget.WidgetName</code>.
     */
    public final TableField<WidgetRecord, String> WIDGETNAME = createField("WidgetName", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Widget.WidgetDescription</code>.
     */
    public final TableField<WidgetRecord, String> WIDGETDESCRIPTION = createField("WidgetDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>Widget.WidgetTypeId</code>.
     */
    public final TableField<WidgetRecord, Integer> WIDGETTYPEID = createField("WidgetTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>Widget</code> table reference
     */
    public Widget() {
        this(DSL.name("Widget"), null);
    }

    /**
     * Create an aliased <code>Widget</code> table reference
     */
    public Widget(String alias) {
        this(DSL.name(alias), WIDGET);
    }

    /**
     * Create an aliased <code>Widget</code> table reference
     */
    public Widget(Name alias) {
        this(alias, WIDGET);
    }

    private Widget(Name alias, Table<WidgetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Widget(Name alias, Table<WidgetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SQLITE_AUTOINDEX_WIDGET_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WidgetRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WIDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WidgetRecord> getPrimaryKey() {
        return Keys.PK_WIDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WidgetRecord>> getKeys() {
        return Arrays.<UniqueKey<WidgetRecord>>asList(Keys.PK_WIDGET);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<WidgetRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<WidgetRecord, ?>>asList(Keys.FK_WIDGET_WIDGETTYPE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Widget as(String alias) {
        return new Widget(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Widget as(Name alias) {
        return new Widget(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Widget rename(String name) {
        return new Widget(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Widget rename(Name name) {
        return new Widget(name, null);
    }
}
