/*
 * This file is generated by jOOQ.
*/
package database.tables;


import database.DefaultSchema;
import database.Indexes;
import database.Keys;
import database.tables.records.WidgettypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Widgettype extends TableImpl<WidgettypeRecord> {

    private static final long serialVersionUID = -177967821;

    /**
     * The reference instance of <code>WidgetType</code>
     */
    public static final Widgettype WIDGETTYPE = new Widgettype();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WidgettypeRecord> getRecordType() {
        return WidgettypeRecord.class;
    }

    /**
     * The column <code>WidgetType.WidgetTypeId</code>.
     */
    public final TableField<WidgettypeRecord, Integer> WIDGETTYPEID = createField("WidgetTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>WidgetType.WidgetTypeName</code>.
     */
    public final TableField<WidgettypeRecord, String> WIDGETTYPENAME = createField("WidgetTypeName", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>WidgetType.WidgetTypeDescription</code>.
     */
    public final TableField<WidgettypeRecord, String> WIDGETTYPEDESCRIPTION = createField("WidgetTypeDescription", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>WidgetType.WidgetTypeNuts</code>.
     */
    public final TableField<WidgettypeRecord, Integer> WIDGETTYPENUTS = createField("WidgetTypeNuts", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WidgetType.WidgetTypeBolts</code>.
     */
    public final TableField<WidgettypeRecord, Integer> WIDGETTYPEBOLTS = createField("WidgetTypeBolts", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>WidgetType.WidgetTypeGears</code>.
     */
    public final TableField<WidgettypeRecord, Integer> WIDGETTYPEGEARS = createField("WidgetTypeGears", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>WidgetType</code> table reference
     */
    public Widgettype() {
        this(DSL.name("WidgetType"), null);
    }

    /**
     * Create an aliased <code>WidgetType</code> table reference
     */
    public Widgettype(String alias) {
        this(DSL.name(alias), WIDGETTYPE);
    }

    /**
     * Create an aliased <code>WidgetType</code> table reference
     */
    public Widgettype(Name alias) {
        this(alias, WIDGETTYPE);
    }

    private Widgettype(Name alias, Table<WidgettypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Widgettype(Name alias, Table<WidgettypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SQLITE_AUTOINDEX_WIDGETTYPE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WidgettypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_WIDGETTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WidgettypeRecord> getPrimaryKey() {
        return Keys.PK_WIDGETTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WidgettypeRecord>> getKeys() {
        return Arrays.<UniqueKey<WidgettypeRecord>>asList(Keys.PK_WIDGETTYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Widgettype as(String alias) {
        return new Widgettype(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Widgettype as(Name alias) {
        return new Widgettype(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Widgettype rename(String name) {
        return new Widgettype(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Widgettype rename(Name name) {
        return new Widgettype(name, null);
    }
}
