/*
 * This file is generated by jOOQ.
*/
package database;


import database.tables.Widget;
import database.tables.Widgettype;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_WIDGET_1 = Indexes0.SQLITE_AUTOINDEX_WIDGET_1;
    public static final Index SQLITE_AUTOINDEX_WIDGETTYPE_1 = Indexes0.SQLITE_AUTOINDEX_WIDGETTYPE_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index SQLITE_AUTOINDEX_WIDGET_1 = createIndex("sqlite_autoindex_Widget_1", Widget.WIDGET, new OrderField[] { Widget.WIDGET.WIDGETID }, true);
        public static Index SQLITE_AUTOINDEX_WIDGETTYPE_1 = createIndex("sqlite_autoindex_WidgetType_1", Widgettype.WIDGETTYPE, new OrderField[] { Widgettype.WIDGETTYPE.WIDGETTYPEID }, true);
    }
}
