/*
 * This file is generated by jOOQ.
*/
package database;


import database.tables.Widget;
import database.tables.Widgettype;
import database.tables.records.WidgetRecord;
import database.tables.records.WidgettypeRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<WidgetRecord, Integer> IDENTITY_WIDGET = Identities0.IDENTITY_WIDGET;
    public static final Identity<WidgettypeRecord, Integer> IDENTITY_WIDGETTYPE = Identities0.IDENTITY_WIDGETTYPE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<WidgetRecord> PK_WIDGET = UniqueKeys0.PK_WIDGET;
    public static final UniqueKey<WidgettypeRecord> PK_WIDGETTYPE = UniqueKeys0.PK_WIDGETTYPE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<WidgetRecord, WidgettypeRecord> FK_WIDGET_WIDGETTYPE_1 = ForeignKeys0.FK_WIDGET_WIDGETTYPE_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<WidgetRecord, Integer> IDENTITY_WIDGET = createIdentity(Widget.WIDGET, Widget.WIDGET.WIDGETID);
        public static Identity<WidgettypeRecord, Integer> IDENTITY_WIDGETTYPE = createIdentity(Widgettype.WIDGETTYPE, Widgettype.WIDGETTYPE.WIDGETTYPEID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<WidgetRecord> PK_WIDGET = createUniqueKey(Widget.WIDGET, "pk_Widget", Widget.WIDGET.WIDGETID);
        public static final UniqueKey<WidgettypeRecord> PK_WIDGETTYPE = createUniqueKey(Widgettype.WIDGETTYPE, "pk_WidgetType", Widgettype.WIDGETTYPE.WIDGETTYPEID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<WidgetRecord, WidgettypeRecord> FK_WIDGET_WIDGETTYPE_1 = createForeignKey(database.Keys.PK_WIDGETTYPE, Widget.WIDGET, "fk_Widget_WidgetType_1", Widget.WIDGET.WIDGETTYPEID);
    }
}
