/*
 * This file is generated by jOOQ.
*/
package database;


import database.tables.SqliteSequence;
import database.tables.Widget;
import database.tables.Widgettype;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>Widget</code>.
     */
    public static final Widget WIDGET = database.tables.Widget.WIDGET;

    /**
     * The table <code>WidgetType</code>.
     */
    public static final Widgettype WIDGETTYPE = database.tables.Widgettype.WIDGETTYPE;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = database.tables.SqliteSequence.SQLITE_SEQUENCE;
}
