/*
 * This file is generated by jOOQ.
*/
package database.tables.records;


import database.tables.Widgettype;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WidgettypeRecord extends UpdatableRecordImpl<WidgettypeRecord> implements Record6<Integer, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -193935437;

    /**
     * Setter for <code>WidgetType.WidgetTypeId</code>.
     */
    public void setWidgettypeid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeId</code>.
     */
    public Integer getWidgettypeid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WidgetType.WidgetTypeName</code>.
     */
    public void setWidgettypename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeName</code>.
     */
    public String getWidgettypename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>WidgetType.WidgetTypeDescription</code>.
     */
    public void setWidgettypedescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeDescription</code>.
     */
    public String getWidgettypedescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>WidgetType.WidgetTypeNuts</code>.
     */
    public void setWidgettypenuts(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeNuts</code>.
     */
    public Integer getWidgettypenuts() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>WidgetType.WidgetTypeBolts</code>.
     */
    public void setWidgettypebolts(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeBolts</code>.
     */
    public Integer getWidgettypebolts() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>WidgetType.WidgetTypeGears</code>.
     */
    public void setWidgettypegears(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>WidgetType.WidgetTypeGears</code>.
     */
    public Integer getWidgettypegears() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Widgettype.WIDGETTYPE.WIDGETTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Widgettype.WIDGETTYPE.WIDGETTYPENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Widgettype.WIDGETTYPE.WIDGETTYPEDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Widgettype.WIDGETTYPE.WIDGETTYPENUTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Widgettype.WIDGETTYPE.WIDGETTYPEBOLTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Widgettype.WIDGETTYPE.WIDGETTYPEGEARS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWidgettypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWidgettypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWidgettypedescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getWidgettypenuts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getWidgettypebolts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getWidgettypegears();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWidgettypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWidgettypename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWidgettypedescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWidgettypenuts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getWidgettypebolts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getWidgettypegears();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value1(Integer value) {
        setWidgettypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value2(String value) {
        setWidgettypename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value3(String value) {
        setWidgettypedescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value4(Integer value) {
        setWidgettypenuts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value5(Integer value) {
        setWidgettypebolts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord value6(Integer value) {
        setWidgettypegears(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgettypeRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WidgettypeRecord
     */
    public WidgettypeRecord() {
        super(Widgettype.WIDGETTYPE);
    }

    /**
     * Create a detached, initialised WidgettypeRecord
     */
    public WidgettypeRecord(Integer widgettypeid, String widgettypename, String widgettypedescription, Integer widgettypenuts, Integer widgettypebolts, Integer widgettypegears) {
        super(Widgettype.WIDGETTYPE);

        set(0, widgettypeid);
        set(1, widgettypename);
        set(2, widgettypedescription);
        set(3, widgettypenuts);
        set(4, widgettypebolts);
        set(5, widgettypegears);
    }
}
