/*
 * This file is generated by jOOQ.
*/
package database.tables.records;


import database.tables.Widget;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WidgetRecord extends UpdatableRecordImpl<WidgetRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 619430591;

    /**
     * Setter for <code>Widget.WidgetId</code>.
     */
    public void setWidgetid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Widget.WidgetId</code>.
     */
    public Integer getWidgetid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Widget.WidgetName</code>.
     */
    public void setWidgetname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Widget.WidgetName</code>.
     */
    public String getWidgetname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Widget.WidgetDescription</code>.
     */
    public void setWidgetdescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Widget.WidgetDescription</code>.
     */
    public String getWidgetdescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>Widget.WidgetTypeId</code>.
     */
    public void setWidgettypeid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>Widget.WidgetTypeId</code>.
     */
    public Integer getWidgettypeid() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Widget.WIDGET.WIDGETID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Widget.WIDGET.WIDGETNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Widget.WIDGET.WIDGETDESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Widget.WIDGET.WIDGETTYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWidgetid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWidgetname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getWidgetdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getWidgettypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWidgetid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWidgetname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWidgetdescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getWidgettypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgetRecord value1(Integer value) {
        setWidgetid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgetRecord value2(String value) {
        setWidgetname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgetRecord value3(String value) {
        setWidgetdescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgetRecord value4(Integer value) {
        setWidgettypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WidgetRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WidgetRecord
     */
    public WidgetRecord() {
        super(Widget.WIDGET);
    }

    /**
     * Create a detached, initialised WidgetRecord
     */
    public WidgetRecord(Integer widgetid, String widgetname, String widgetdescription, Integer widgettypeid) {
        super(Widget.WIDGET);

        set(0, widgetid);
        set(1, widgetname);
        set(2, widgetdescription);
        set(3, widgettypeid);
    }
}
